#!/bin/bash

SRC=$PWD/src
WD=$PWD

######################################################################
##																	##
## 				RUN EVERY TIME A PACKAGE IS ADDED		            ##
##																	##
######################################################################


# === UPDATE BINARIES
X86=$PWD/x86_64

for dir in $SRC/*; do
    (cd $dir && PKGDEST=$X86 makepkg -cf )
    echo "$dir"
done


# === UPDATE DB
(cd $X86 && repo-add 'custom.db.tar.gz' *.pkg.tar.zst)

# === UPDATE STATIC SITE
./static_generator .
